name: dartgapost
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  amplify_api: ^1.0.0-0
  amplify_auth_cognito: ^1.0.0-0
  amplify_authenticator: ^1.0.0-0
  amplify_flutter: ^1.0.0-0
  amplify_storage_s3: ^1.0.0-0
  file_picker: ^5.2.7
  flutter:
    sdk: flutter
  go_router: ^6.5.5

dev_dependencies:
  amplify_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
